### ISSUE TITLE
Syntax test of several sources fails

### ISSUE THREAD

**Issue by spirillen** [PyFunceble/docker#2]
Test line:

`docker run -it pyfunceble/pyfunceble-dev -f https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/snuff-hosts https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts --display-status INVALID --syntax --no-files`

<details><summary>Error: output</summary>

Unable to find image 'pyfunceble/pyfunceble-dev:latest' locally
latest: Pulling from pyfunceble/pyfunceble-dev
955615a668ce: Pull complete 
2756ef5f69a5: Pull complete 
911ea9f2bd51: Pull complete 
27b0a22ee906: Pull complete 
8584d51a9262: Pull complete 
524774b7d363: Pull complete 
af193b9b3d11: Pull complete 
aacb0e56e8f3: Pull complete 
46cd7abc9e93: Pull complete 
f1637ffa9982: Pull complete 
f372b51622ba: Pull complete 
204b31ef6016: Pull complete 
005ee9515d72: Pull complete 
5bde20c1eee0: Pull complete 
87fee461594a: Pull complete 
b790b37a05a0: Pull complete 
Digest: sha256:ca886634bbcd9146bbe4ec2fce55c97db0316e39eea40065785b0875da28c134
Status: Downloaded newer image for pyfunceble/pyfunceble-dev:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff4626340a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /PyFunceble/iana/master/iana-domains-db.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff4626340a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/PyFunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 55, in <module>
    import PyFunceble.factory
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/factory.py", line 55, in <module>
    Requester = requester()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/requests/requester.py", line 119, in __init__
    self.session = self.get_session()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/requests/requester.py", line 411, in get_session
    RequestHTTPSAdapter(max_retries=self.max_retries, timeout=self.timeout),
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/requests/adapter/base.py", line 83, in __init__
    self.dns_query_tool = DNSQueryTool().guess_all_settings()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 122, in __init__
    self.nameservers.guess_and_set_nameservers()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/dns/nameserver.py", line 244, in guess_and_set_nameservers
    self.set_nameservers(dns.resolver.get_default_resolver().nameservers)
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/dns/nameserver.py", line 208, in set_nameservers
    for dns_ip in self.get_ip_from_nameserver(server):
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/query/dns/nameserver.py", line 127, in get_ip_from_nameserver
    if cls.domain_syntax_checker.set_subject(nameserver).is_valid():
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 143, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain.py", line 110, in is_valid
    return self.is_valid_second_level() or self.is_valid_subdomain()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 143, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain.py", line 118, in is_valid_second_level
    return self.second_level_checker.is_valid()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 143, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/syntax/second_lvl_domain.py", line 92, in is_valid
    extension not in self.iana_dataset
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/dataset/iana.py", line 78, in __contains__
    return value in self.get_content()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/dataset/base.py", line 109, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/dataset/base.py", line 134, in get_content
    self.DOWNLOADER.start()
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/downloader/base.py", line 285, in start
    if DownloadHelper(self.download_link).download_text(
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/helpers/download.py", line 235, in download_text
    req = session.get(self.url, verify=self.certificate_validation)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /PyFunceble/iana/master/iana-domains-db.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff4626340a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

</details>

**Comment by funilrys** [comment]
@spirillen GitHub not reachable? That happens sometimes...

The same command is working here.

**Comment by funilrys** [comment]
By the way @spirillen, 

in the next version of the docker image you will be able to do:

```
- echo hello 
- "--version" 
```

in your GL jobs.
